---
- name: Create NetBox deploy directory
  ansible.builtin.file:
    path: "{{ netbox_deploy_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create env directory
  ansible.builtin.file:
    path: "{{ netbox_env_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ netbox_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy configuration files to host
  ansible.builtin.copy:
    src: "configuration/{{ item }}"
    dest: "{{ netbox_config_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - configuration.py
    - extra.py
    - logging.py
    - plugins.py
