---
- name: Preflight checks
  ansible.builtin.import_tasks: preflight.yml
  tags: [netbox, preflight]

- name: Create directory layout
  ansible.builtin.import_tasks: directories.yml
  tags: [netbox, directories]

- name: Deploy docker-compose.yml
  ansible.builtin.import_tasks: compose.yml
  tags: [netbox, compose]

- name: Template env files
  ansible.builtin.import_tasks: env.yml
  tags: [netbox, env]

- name: Manage service state
  ansible.builtin.import_tasks: service.yml
  tags: [netbox, service]
