---
- name: Manage NetBox compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ netbox_deploy_dir }}"
    project_name: "{{ netbox_compose_project_name }}"
    files:
      - docker-compose.yml
      - docker-compose.overlay.yml
    state: "{{ netbox_compose_state }}"
    wait: true
    wait_timeout: "{{ netbox_compose_wait_timeout }}"
